# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jaqribei <jaqribei@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/27 13:14:23 by jaqribei          #+#    #+#              #
#    Updated: 2023/09/27 13:54:01 by jaqribei         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = so_long

HEADER =

CC = CC

FLAGS = -Wall -Werror -Wextra -g3

INCLUDES = 

LIBX = -lmlx -lXext -lX11

SRC:

SRC_OBJ:

all:

clean:

fclean:

re:


